### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/pygraphviz-feedstock/pull/18

**Pull request closed without merging**
